feat: Support Google Blockly theme
roroettg/ngx-blockly pull request #3
Opened 2019-08-04 06:00 UTC by kencwlau

According to the update of Google Blockly in April 2019, themes provide 
a customized way to define look and feel for blocks and categories.
Thus, this commit add support to the block and category styles.

Reference: https://developers.google.com/blockly/guides/configure/web/themes

2019-08-06 08:05 UTC, roroettg commented
Thank you for your PR. I will review it as soon as i can.

2019-08-06 09:34 UTC, roroettg requested changes
Would you mind updating the README.md and write a short example on how to use your code.

It would also be nice if you could adress the linter issues in the code.

2019-08-06 09:34 UTC, roroettg commented on projects/ngx-blockly/src/lib/ngx-blockly/models/category.ts
> +            xml += `colour="${this.colour}" `
Missing semicolon

2019-08-06 09:34 UTC, roroettg commented on projects/ngx-blockly/src/lib/ngx-blockly/models/category.ts
> +            xml += `categorystyle="${this.style}" `
Missing semicolon

2019-08-06 09:37 UTC, kencwlau commented
> @roroettg  I will update the Readme.md and improve the coding quality as you suggested within these days. Thank you for your review!

2019-08-11 03:00 UTC, kencwlau commented
@roroettg I have fixed the semicolon issue and add the Style part in the README.md, please review the changes, thanks!

2019-08-12 09:57 UTC, roroettg commented
Thank your for your changes. I am currently on vacation and I will review your changes within the next week.

2019-08-22 08:57 UTC, merged

2019-08-22 08:58 UTC, roroettg commented
Sorry, for the delay. I reviewed and tested your pull request and everything looks fine. Thanks again for your contribution.